name: Hello GitHub Actions

on:
  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 가져오기
        uses: actions/checkout@v4

      - name: Hello 출력
        run: echo "Hello, Github Actions!"

      - name: multiple commands
        run: |
          echo "Good"
          echo "Morning"
          echo "!"
        
      - name: Print GitHub Context Variables 
        run: | 
          echo "Repository: $GITHUB_REPOSITORY" 
          echo "Ref: $GITHUB_REF" 
          echo "SHA: $GITHUB_SHA" 
          echo "Actor: $GITHUB_ACTOR" 
          echo "Workflow: $GITHUB_WORKFLOW" 
          echo "Run ID: $GITHUB_RUN_ID" 
          echo "Run Number: $GITHUB_RUN_NUMBER" 
          echo "Work Directory: $GITHUB_WORKSPACE"